# check ./tina/utils/constant.py
model_post_train_dataset_name: curated_limr_full_divers_24(temp_schedule_lowLR_lessedcay)
model_post_train_type: grpo
rl_post_train_reward_funcs:
- strong_format
- accuracy
rl_post_train_reward_weights:
- 1.0
- 2.0


# Model configs from trl
model_name_or_path: Qwen/Qwen2.5-Math-1.5B
attn_implementation: flash_attention_2
use_peft: false


# GRPO trainer configs from trl
bf16: true
use_vllm: true
vllm_device: cuda:0
vllm_gpu_memory_utilization: 0.45
vllm_max_model_len: 4096
gradient_accumulation_steps: 8 # 看起来到后期reward收敛了，那不如少一半step
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
log_completions: true
push_to_hub: false
hub_strategy: every_save
hub_private_repo: true
hub_model_id: dpsk-rl-diversGRPO

learning_rate: 5e-06
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.5
max_prompt_length: 512
max_completion_length: 4096
max_steps: 360 # use 360 for lr scheduler but stop at 180 steps
num_generations: 8
num_train_epochs: 2
overwrite_output_dir: true
per_device_train_batch_size: 4
report_to:
- wandb

save_strategy: steps
save_steps: 25
save_total_limit: 1
save_weights_only_checkpoint: true

seed: 42
temperature: 1
warmup_ratio: 0.1

use_custom_temp_sampling: true
base_sampling_temperature: 0.6
use_positional_temp_sampling: true
positional_temp_config: [(0, 1.6)]
use_conditional_token_temp_sampling: true
conditional_temp_trigger_token_ids: [10061, 3197, 1205, 1249] # 口癖
conditional_temp_value: 1.0
use_token_template_temp_sampling: true
template_temp_config: 
  - [[624], 1.2]
  - [[4192], 1.2]
  - [[382], 1.2]
  - [[271], 1.2]
  - [[1939], 1.2]
  - [[5267], 1.2]
  - [[30831], 1.2]
  - [[27901], 1.2]
  - [[2219], 1.2]
  - [[4894], 1.2]
  - [[10061], 1.2]
  - [[3197], 1.2]
  - [[1205], 1.2]
  - [[1249], 1.2]
use_temp_scheduler: true
temp_warmup_ratio: 0.1
temp_num_cycles: 3

# (624, '.\n')  (4192, '.\n\n\n') (382, '.\n\n')
# (271, '\n\n') (198, '\n') 观察到公式中有
# First, let's expand the expression:
# \[
# (xy + z)(xz + y) = x^2yz + xy^2 + xz^2 + y^2z
# \] 这里的换行似乎是有必要的，因此删掉这里之后的高温采样

# (1939, '?\n\n') (5267, '?\n') (30831, '?\n\n\n')
# (27901, '!\n\n\n') (2219, '!\n\n') (4894, '!\n')
# 口癖： (10061, 'Let') (3197, ' When') (1205, ' We') (1249, 'To')